### ISSUE TITLE
Dublicated SSID causes a endless loop

### ISSUE THREAD

**Issue by nodi-andy** [warmcat/lws-esp32-factory#16]
It s a minor bug from : commit d4969b877502fb7b905aa537525c4b29ba9e8bc8: sorry not tested the current version.

I have a router and a forwarder, which have same SSID, this drives esp32 into a endless loop that it switches with 2s periods between wifi sources.

this was only in case of first init of system, after uploading the FW "test-server-demos", works right now good with dublicated ssid

**Comment by lws-team** [comment]
I think this is related to the scan behaviour in -factory.  If you're connected to the ESP32 as the AP, it's really sensitive to going away and scanning on other channels.  If it's still happening please follow up otherwise closing for now.
