### ISSUE TITLE
How to disable SSL

### ISSUE THREAD

**Issue by nodi-andy** [warmcat/lws-esp32-factory#21]
Hi,

this is not an "issue" but a question.

I am missing in the documentation, how can i use port 80 without encryption. Solely chaning info.port on 80 doesnt work.

Thanks in advice

**Comment by lws-team** [comment]
You mean SSL (aka tls)... ssh is actually supported in lws by a provided plugin.

Setting the port is half the job, to disable tls you also need to

```
               info.port = 80;
               info.options &= ~LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
```

and also maybe

```
        info.ssl_cert_filepath = NULL;
        info.ssl_private_key_filepath = NULL;
```
