### ISSUE TITLE
oto_choose_part will accept partition outside range

### ISSUE THREAD

**Issue by jas39** [warmcat/lws-esp32-factory#34]
I believe that the following statement on line 75 in protocol_esp32_lws_ota.c should be changed from:
		if (part->subtype < ESP_PARTITION_SUBTYPE_APP_OTA_MIN ||
		    part->subtype >= ESP_PARTITION_SUBTYPE_APP_OTA_MIN +
		    		     ESP_PARTITION_SUBTYPE_APP_OTA_MAX)
			goto next;

to:
		if (part->subtype < ESP_PARTITION_SUBTYPE_APP_OTA_MIN ||
		    part->subtype >= ESP_PARTITION_SUBTYPE_APP_OTA_MAX)
			goto next;

Since definition of ESP_PARTITION_SUBTYPE_APP_OTA_MAX is:
ESP_PARTITION_SUBTYPE_APP_OTA_MAX = ESP_PARTITION_SUBTYPE_APP_OTA_MIN + 16,//!< Max subtype of OTA partition

**Comment by FredrikFornstad** [comment]
It seems that this fix has been implemented a few months ago, so I guess this issue can be closed...

**Comment by jas39** [comment]
Agree
