### ISSUE TITLE
Please give me an esp8266 program about LWS

### ISSUE THREAD

**Issue by Mr-99** [warmcat/lws-esp32-factory#56]

**Comment by lws-team** [comment]
... the stuff was removed several versions ago and isn't supported... I don't have any esp8266 device any more and no reason to spend time on it.

If you want to look at it in lws, it's there in the git history, it was removed after v2.4, so v2.4-stable has it

https://libwebsockets.org/git/libwebsockets/tree/lib/plat/lws-plat-esp8266.c?h=v2.4-stable

... but you are on your own with it.  Obviously it hasn't been tested on recent esp-idf stuff.  There's no developed equivalent of the -factory app for it, just the core lws support.
