### ISSUE TITLE
No .der SSL certificates found

### ISSUE THREAD

**Issue by Scalpel78** [warmcat/lws-esp32-factory#6]
After doing a successful 

    make all flash monitor

and accessing the /factory.html webpage I'm trying to find the .der files to upload. According to the documentation they should have been generated in the top-level of the project, but there are no *.der files there.

Did a 

    find | grep der
to find them, but no sign of them.

Are there any prerequisites that are required that I might be missing?

**Comment by lws-team** [comment]
I have updated -factory to take PEM certs, which you can find in build/libwebsockets/ and updated the README accordingly.
