### ISSUE TITLE
Usage in c++/ small code change

### ISSUE THREAD

**Issue by johsely1234** [warmcat/lws-esp32-factory#7]
To use it in c++ with the compiler option -fpermissive I need to add a cast to the following line:

`515 struct timer_mapping *tm = malloc(sizeof(*tm));`

to

`515 struct timer_mapping *tm = (timer_mapping*)malloc(sizeof(*tm));`

Would be a small change.

**Comment by lws-team** [comment]
This is in lws master now (and -factory and -test-server-demos aligned to that).
